### ISSUE TITLE
Broken link for "PDF Status"

### ISSUE THREAD

**Issue by NGenetzky** [NorfairKing/cn-cards#1]
1. Click [PDF Status](https://www.sharelatex.com/github/repos/NorfairKing/cn-cards/builds/latest/output.pdf)
2. See

> Not found
>
> Sorry, we can't find the page you are looking for.

**Comment by NorfairKing** [comment]
This service went under a long time ago. The 'fix' would be to remove that link. Best to try to build this yourself.

**Comment by NGenetzky** [comment]
> This service went under a long time ago. 

That's a shame. I suppose that's how things go sometimes.

> The 'fix' would be to remove that link.

I think that would be reasonable.

> Best to try to build this yourself.

I was curious, but not quite that curious - it seemed interesting.

---

More than anything I feel that if I had a broken link that was on a published project then I would love for someone to notify me, and so I decided to do so in this case. If it's not a concern for you, then please feel free to close without action.

**Comment by NorfairKing** [comment]
"fixed" in 839cd114f8a44219407fb2ed7a3354500d455ad4
